version: '3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      db.driverClass: 'com.mysql.cj.jdbc.Driver'
      db.url: 'jdbc:mysql://mysql:3306/lavanderia'
      db.username: 'root'
      db.password: 'root'
      redis.host: 'redis'
      redis.port: '6379'
    networks:
      - network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lavanderia
    ports:
      - '3306:3306'
    networks:
      - network

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - network
networks:
  network: